services:
  user-service-db:
    image: postgres:16
    container_name: user-service-db
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12gonzik09
    ports:
      - "5432:5432"
    volumes:
      - user_service_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: userservice-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  user_service_data:
  redis-data:
